# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/user_module.html

- name: Create user with sudo privileges and SSH key
  hosts: jenkins
  become: yes

  tasks:
    - name: Create user
      ansible.builtin.user:
        name: cloud
        password: "{{ 'Qq123456' | password_hash('sha512') }}"
        state: present
        createhome: yes
        shell: /bin/bash

    - name: Create a 2048-bit SSH key for user cloud in /home/cloud/.ssh/id_rsa
      ansible.builtin.user:
        name: cloud
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: /home/cloud/.ssh/id_rsa

    - name: Add user to sudo group
      user:
        name: cloud
        groups: sudo
        append: yes
