# https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_intro.html

---
- name: Install and configure nginx for React Web App
  hosts: nginx
  become: true

  tasks:
  - name: Clone the repository
    git:
      repo: 'https://github.com/justgithubaccount/welcome-tg-app-front.git'
      dest: '/home/stage'

  - name: Installing nodejs
    apt: name=nodejs update_cache=yes

  - name: Installing npm
    apt: name=npm update_cache=yes

  - name: Installing dependencies
    command: npm install
    args:
      chdir: /home/stage

  - name: Building
    command: npm run build
    args:
      chdir: /home/stage

  - name: Installing nginx
    apt: name=nginx state=latest

  - name: Copying build files to nginx directory
    copy:
      src: /home/stage/build
      dest: /var/www/html
      remote_src: true

  - name: Copy nginx configuration file
    copy:
      src: ./nginx.conf
      dest: /etc/nginx/nginx.conf
      owner: root
      group: root
      mode: '0644'

  - name: Starting nginx
    service:
      name: nginx
      state: started
